version: "2"

services:
  stigviewer:
    build:
      context: ./stigviewer
    command: java -jar STIGViewer-2.9.jar
    container_name: stigviewer
    image: stigviewer:test
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/rfirstaid/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY
